HttpServer:
  Port: 8080

Database:
  Main:
    Host: '127.0.0.1'
    SslMode: 'disable'
    Port: 5432
    User: 'postgres'
    Password: 'postgres'
    DbName: 'person'
  Replica:
    Host: '127.0.0.1'
    SslMode: 'disable'
    Port: 5432
    User: 'postgres'
    Password: 'postgres'
    DbName: 'person'