HttpServer:
  Port: 8080

Database:
  Main:
    Host: '127.0.0.1'
    DbName: 'postgres'
    User: 'postgres'
    Password: 'postgres'
    SslMode: 'disable'

  Replica:
    Host: '127.0.0.1'
    DbName: 'postgres'
    User: 'postgres'
    Password: 'postgres'
    SslMode: 'disable'